name: Terraform Infrastructure

on:
  push:
    branches:
      - dev
      - stage
      - production
  pull_request:
    branches:
      - dev
      - stage
      - production

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.3

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=tfstatejm07" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=infra-${GITHUB_REF_NAME}.tfstate"

      - name: Force unlock Terraform state (temporary)
        run: terraform force-unlock -force facfcb71-6daf-181b-e89a-7507244b7567 || echo "No lock found or already released"

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/stage' || github.ref == 'refs/heads/production'
        run: terraform apply -auto-approve tfplan